{% set name = "pysdf" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d0639838ec3adcee3499d37290cda217fc1f0834e30a4167da04ae062087fa7b

build:
  number: 2
  script:
    - set "CL=/FIchrono %CL%"  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake >=3.16,<3.27
    - eigen
    - packaging         # [target_platform != build_platform]
    - pip               # [target_platform != build_platform]
    - pybind11 >=2.5.0  # [target_platform != build_platform]
    - python            # [target_platform != build_platform]
    - setuptools        # [target_platform != build_platform]
    - wheel             # [target_platform != build_platform]
  host:
    - pip
    - pybind11 >=2.5.0
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pysdf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sxyu/sdf
  summary: Parallelized triangle mesh --> continuous signed distance field on CPU
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jeongseok-meta
